### ISSUE TITLE
Compilation Error : build bacon -> Failed: bacon

### ISSUE THREAD

**Issue by shank03** [Havoc-OS/android_manifest#12]
I type this command to start compilation 
`. build/envsetup.sh`
`brunch` and then select my build i.e. full-eng

And then.. this is the error I get all the time :
`[100% 1/1] build bacon
FAILED: bacon 
/bin/bash -c "(ln -f  /home/shank/havoc_pie/out/target/product/generic/.zip ) && (md5sum /home/shank/havoc_pie/out/target/product/generic/.zip | sed \"s|/home/shank/havoc_pie/out/target/product/generic/||\" > /home/shank/havoc_pie/out/target/product/generic/.zip.md5sum ) && (./vendor/havoc/tools/generate_ota_info.sh /home/shank/havoc_pie/out/target/product/generic/.zip ) && (echo \"Package Complete: /home/shank/havoc_pie/out/target/product/generic/.zip\" >&2 )"
ln: /home/shank/havoc_pie/out/target/product/generic/.zip: No such file or directory
ninja: build stopped: subcommand failed.
22:30:46 ninja failed with: exit status 1`

Please help me :(  ... I am trying to solve this for hours.. am I doing something wrong ?

**Comment by havocdeveloper** [comment]
Bro I'm getting this error

`- bash: /root/havoc/vendor/havoc/build/envsetup.sh: No such file or directory`

**Comment by shank03** [comment]
Bro .. go to desktop open terminal and try typing exactly this.. 

cd havoc
. build/envsetup.sh

If this doesn't work, . Type this from desktop terminal,

cd havoc
source build/envsetup.sh

If you still get error, then open terminal in desktop and type this,

cd havoc
repo sync
. build/envsetup.sh

**Comment by hariprasad17** [comment]
> I type this command to start compilation
> `. build/envsetup.sh`
> `brunch` and then select my build i.e. full-eng
> 
> And then.. this is the error I get all the time :
> `[100% 1/1] build bacon FAILED: bacon /bin/bash -c "(ln -f /home/shank/havoc_pie/out/target/product/generic/.zip ) && (md5sum /home/shank/havoc_pie/out/target/product/generic/.zip | sed \"s|/home/shank/havoc_pie/out/target/product/generic/||\" > /home/shank/havoc_pie/out/target/product/generic/.zip.md5sum ) && (./vendor/havoc/tools/generate_ota_info.sh /home/shank/havoc_pie/out/target/product/generic/.zip ) && (echo \"Package Complete: /home/shank/havoc_pie/out/target/product/generic/.zip\" >&2 )" ln: /home/shank/havoc_pie/out/target/product/generic/.zip: No such file or directory ninja: build stopped: subcommand failed. 22:30:46 ninja failed with: exit status 1`
> 
> Please help me :( ... I am trying to solve this for hours.. am I doing something wrong ?

What is the solution for this error?

**Comment by shank03** [comment]
Not to select `full-eng`.

Lunch your device, and either userdebug or user build
