### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by havocdeveloper** [Havoc-OS/android_manifest#15]
While running . build/envsetup.sh command. I'm getting this error -bash: /root/havoc/vendor/havoc/build/envsetup.sh: No such file or directory

I'm using Ubuntu 14.04

**Comment by shank03** [comment]
Bro .. go to desktop open terminal and try typing exactly this..

cd havoc
. build/envsetup.sh

If this doesn't work, . Type this from desktop terminal,

cd havoc
source build/envsetup.sh

If you still get error, then open terminal in desktop and type this,

cd havoc
repo sync
. build/envsetup.sh

**Comment by havocdeveloper** [comment]
Thanks bro.

Now I'm getting this issue
`can not locate config makefile for product "havoc_vince".`
