### ISSUE TITLE
No build menu

### ISSUE THREAD

**Issue by cris-** [Havoc-OS/android_manifest#17]
After setting up the build environment as described in [README.mkdn](https://raw.githubusercontent.com/Havoc-OS/android_manifest/ten/README.mkdn) I've executed
```bash
   . build/envsetup.sh
    brunch
```
I'm not getting a menu with the available choices, but the following output:
```bash

You're building on Linux

Lunch menu... pick a combo:
11:16:54 Build sandboxing disabled due to nsjail error. This may become fatal in the future.
11:16:54 Please let us know why nsjail doesn't work in your environment at:
11:16:54   https://groups.google.com/forum/#!forum/android-building
11:16:54   https://issuetracker.google.com/issues/new?component=381517

Which would you like? [aosp_arm-eng] 
```

Continuing the build using the suggested option leads to the following error:
```bash
error: vendor/havoc/build/soong/Android.bp:30:8: module "generated_kernel_includes": cmd: unknown variable '$(PATH_OVERRIDE_SOONG)'
11:25:17 soong bootstrap failed with: exit status 1

#### failed to build some targets (27 seconds) ####
```

Note: I'm attempting to build on Debian Testing and on the same system the LineageOS build is working without problems.

**Comment by ghost** [comment]
Did you got a fix? If yes please tell me how :D

**Comment by VTVishwanath** [comment]
Is this already fixed? I am still facing this issue. Any help would be appreciated. @ghost and @cris-
