### ISSUE TITLE
LineageParts is undefined

### ISSUE THREAD

**Issue by edgars-cirulis** [Havoc-OS/android_manifest#20]
error: packages/apps/LineageParts/Android.bp:17:1: "LineageParts" depends on undefined module "org.lineageos.platform.internal"

**Comment by Prasanna-16** [comment]
did you figured out how to solve this?
please tell I am stuck at this.

**Comment by neural0x** [comment]
you need to clone lineage-sdk

`git clone https://github.com/LineageOS/android_lineage-sdk/ lineage-sdk`

**Comment by xc112lg** [comment]
tha

> you need to clone lineage-sdk
> 
> `git clone https://github.com/LineageOS/android_lineage-sdk/ lineage-sdk`

thanks

**Comment by xc112lg** [comment]
> you need to clone lineage-sdk
> 
> `git clone https://github.com/LineageOS/android_lineage-sdk/ lineage-sdk`

i get this error when i use it FAILED: out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/package-res.apk out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/proguard.options out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/android/R.srcjar out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/R.txt out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/extra_packages
rm -rf out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/aapt2/R && out/host/linux-x86/bin/aapt2 link -o out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/package-res.apk --private-symbols org.lineageos.platform.internal --no-auto-version --auto-add-overlay --allow-reserved-package-id --package-id 63 --no-static-lib-packages --manifest out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/manifest_fixer/AndroidManifest.xml  --min-sdk-version 34 --target-sdk-version 34 --version-code 34 --version-name  14 --product default -c en_US,en_US,af_ZA,am_ET,ar_EG,ar_XB,as_IN,az_AZ,be_BY,bg_BG,bn_BD,bs_BA,ca_ES,cs_CZ,da_DK,de_DE,el_GR,en_AU,en_CA,en_GB,en_IN,en_XA,es_ES,es_US,et_EE,eu_ES,fa_IR,fi_FI,fr_CA,fr_FR,gl_ES,gu_IN,hi_IN,hr_HR,hu_HU,hy_AM,in_ID,is_IS,it_IT,iw_IL,ja_JP,ka_GE,kk_KZ,km_KH,kn_IN,ko_KR,ky_KG,lo_LA,lt_LT,lv_LV,mk_MK,ml_IN,mn_MN,mr_IN,ms_MY,my_MM,nb_NO,ne_NP,nl_NL,or_IN,pa_IN,pl_PL,pt_BR,pt_PT,ro_RO,ru_RU,si_LK,sk_SK,sl_SI,sq_AL,sr_Latn_RS,sr_RS,sv_SE,sw_TZ,ta_IN,te_IN,th_TH,tl_PH,tr_TR,uk_UA,ur_PK,uz_UZ,vi_VN,zh_CN,zh_HK,zh_TW,zu_ZA,en_XC,normal --preferred-density 560dpi --java out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/aapt2/R --proguard out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/proguard.options --output-text-symbols out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/R.txt @out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/aapt2/res.list -R @out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/aapt2/overlay.list && out/host/linux-x86/bin/soong_zip -write_if_changed -jar -o out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/android/R.srcjar -C out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/aapt2/R -D out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/aapt2/R &&out/host/linux-x86/bin/extract_jar_packages -i out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/gen/android/R.srcjar -o out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/extra_packages --prefix '--extra-packages '
out/soong/.intermediates/lineage-sdk/org.lineageos.platform-res/android_common/manifest_fixer/AndroidManifest.xml:20: error: attribute android:sharedUserId not found.
