### ISSUE TITLE
compile a specific version, no tags

### ISSUE THREAD

**Issue by bdhay** [Havoc-OS/android_manifest#34]
is it possible to compile a specific version? the Havoc-OS/android_manifest repo does not seem to be tagged in any way.

**Comment by Sarisan** [comment]
If you talking about how to build with GApps then just add this to havoc_device.mk
`WITH_GAPPS := true` and  `TARGET_GAPPS_ARCH := arm64` or `TARGET_GAPPS_ARCH := arm`, also you can write these in terminal before `brunch`, using `export` like `export WITH_GAPPS := true`

You must make clean build after switched to gapps or without

**Comment by bdhay** [comment]
nope. what i mean is Skulshady (Anushek) announces releases from time to time, but i can't find tags for them. what if i want to build Havoc-3.6 instead of current Havoc-3.7 ?

**Comment by SKULSHADY** [comment]
These repos are rebased multiple times so no point marking releases

**Comment by bdhay** [comment]
@SKULSHADY 
so how can i go and repo sync to a previous release?
